### ISSUE TITLE
Question: is it possible to get online categories for a navigation menu

### ISSUE THREAD

**Issue by kroneman** [mobify/commercecloud-ocapi-client#12]
Heya,

Been testing out this repo with my current sandbox.

I'm trying to get the categories to render a main navigation menu.

Is it possible to get all the online categories for a specified site via the apis documented in
https://mobify.github.io/commercecloud-ocapi-client/?

I've been reading through the documentation but can't seem to find a method.

thanks in advance.

**Comment by ranveer5289** [comment]
Hey,

I am not entirely sure but did you tried `getCategoriesByID` using category ID `root` ?

Thanks

**Comment by kroneman** [comment]
yep, that works.

Thanks!
